DB:
  - name: couchbase
  - name: postgres
  - name: redis
  - name: mysql
  - name: mongo
  - name: mariadb
  - name: memcached
  - name: aerospike
  - name: influxdb
  - name: crate
  - name: cassandra
  - name: couchdb
  - name: adminer
  - name: neo4j
  - name: rethinkdb
  - name: owncloud
  - name: arangodb
  - name: orientdb
